# -*- coding: utf-8 -*-
"""train_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFg9dGCqXpNqzJnRpWD5yIjE8R7ulpoM
"""

!unzip -q dataset.zip

!pip install pytorch_lightning
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, models, transforms
import pytorch_lightning as pl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, classification_report
import numpy as np
import torchmetrics
from pytorch_lightning.loggers import CSVLogger


preprocess = models.ResNet50_Weights.DEFAULT.transforms()

train_transform = transforms.Compose([
    transforms.RandomHorizontalFlip(),
    transforms.ColorJitter(brightness=[0.5, 1.5], contrast=[0.8, 1.2]),
    preprocess
])

val_test_transform = transforms.Compose([preprocess])


batchsize = 32
trainset = datasets.ImageFolder(root='./dataset/train', transform=train_transform)
valset = datasets.ImageFolder(root='./dataset/validation', transform=val_test_transform)
testset = datasets.ImageFolder(root='./dataset/test', transform=val_test_transform)

trainloader = DataLoader(trainset, batch_size=batchsize, shuffle=True)
valloader = DataLoader(valset, batch_size=batchsize, shuffle=False)
testloader = DataLoader(testset, batch_size=batchsize, shuffle=False)

class_names = trainset.classes


num_classes = 3
model = models.resnet50(weights=models.ResNet50_Weights.DEFAULT)


for param in model.parameters():
    param.requires_grad = False


num_features = model.fc.in_features
model.fc = nn.Linear(num_features, num_classes)


class LitModel(pl.LightningModule):
    def __init__(self, model, lr=1e-3):
        super().__init__()
        self.model = model
        self.criteria = nn.CrossEntropyLoss()
        self.lr = lr

        self.train_accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)
        self.val_accuracy = torchmetrics.Accuracy(task="multiclass", num_classes=num_classes)

    def forward(self, x):
        return self.model(x)

    def training_step(self, batch, batch_idx):
        inputs, labels = batch
        outputs = self(inputs)
        loss = self.criteria(outputs, labels)
        self.log("train_loss", loss, on_step=False, on_epoch=True, prog_bar=True)

        preds = torch.argmax(outputs, dim=1)
        self.train_accuracy.update(preds, labels)
        self.log("train_acc", self.train_accuracy, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def validation_step(self, batch, batch_idx):
        inputs, labels = batch
        outputs = self(inputs)
        loss = self.criteria(outputs, labels)
        self.log("val_loss", loss, on_step=False, on_epoch=True, prog_bar=True)

        preds = torch.argmax(outputs, dim=1)
        self.val_accuracy.update(preds, labels)
        self.log("val_acc", self.val_accuracy, on_step=False, on_epoch=True, prog_bar=True)
        return loss

    def configure_optimizers(self):
        return torch.optim.Adam(self.parameters(), lr=self.lr)


lit_model = LitModel(model, lr=1e-3)
logger = CSVLogger("logs", name="laundry_model")
trainer = pl.Trainer(max_epochs=10, accelerator="auto", devices="auto", log_every_n_steps=5, logger=logger)

print("Beginning Training Phase...")
trainer.fit(lit_model, train_dataloaders=trainloader, val_dataloaders=valloader)


torch.save(model.state_dict(), 'new_laundry_resnet50.pth')
print("Saved local weights as new_laundry_resnet50.pth")


lit_model.eval()
all_preds = []
all_labels =[]

with torch.no_grad():
    for images, labels in testloader:
        images = images.to(lit_model.device)
        outputs = lit_model(images)
        _, predicted = torch.max(outputs.data, 1)
        all_preds.extend(predicted.cpu().numpy())
        all_labels.extend(labels.numpy())


print("\n--- Precision and Recall Report ---")
print(classification_report(all_labels, all_preds, target_names=class_names))


cm = confusion_matrix(all_labels, all_preds)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
plt.title('Laundry AI Confusion Matrix')
plt.xlabel('Predicted Label')
plt.ylabel('True Label')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os


log_dir = 'logs/laundry_model'
version_dirs = [d for d in os.listdir(log_dir) if d.startswith('version_')]
latest_version_dir = os.path.join(log_dir, sorted(version_dirs, key=lambda x: int(x.split('_')[1]))[-1])
metrics_path = os.path.join(latest_version_dir, 'metrics.csv')


metrics_df = pd.read_csv(metrics_path)


metrics_df.fillna(method='ffill', inplace=True)


plt.figure(figsize=(12, 6))
sns.lineplot(data=metrics_df, x='epoch', y='train_loss', label='Training Loss')
sns.lineplot(data=metrics_df, x='epoch', y='val_loss', label='Validation Loss')
plt.title('Training and Validation Loss Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.legend()
plt.show()


plt.figure(figsize=(12, 6))
sns.lineplot(data=metrics_df, x='epoch', y='train_acc', label='Training Accuracy')
sns.lineplot(data=metrics_df, x='epoch', y='val_acc', label='Validation Accuracy')
plt.title('Training and Validation Accuracy Over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)
plt.legend()
plt.show()